"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import os

from pathlib import Path
from dotenv import load_dotenv


# ============================================================
# BASE DIRECTORY
# ============================================================

BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env for local development.
# Production hosting platforms should provide these variables
# through their environment-variable settings.
load_dotenv(BASE_DIR / '.env')


# ============================================================
# SECURITY
# ============================================================

# Secret key is stored in the environment.
SECRET_KEY = os.getenv('SECRET_KEY')

if not SECRET_KEY:
    raise RuntimeError(
        'SECRET_KEY environment variable is not configured.'
    )


# Debug mode is controlled through the environment.
DEBUG = os.getenv('DEBUG', 'False').lower() == 'true'


# ============================================================
# ALLOWED HOSTS
# ============================================================

# Local development works with localhost and 127.0.0.1.
#
# For deployment, set:
#
# ALLOWED_HOSTS=your-domain.com,www.your-domain.com
#
# Multiple hosts should be comma-separated.
ALLOWED_HOSTS = [
    host.strip()
    for host in os.getenv(
        'ALLOWED_HOSTS',
        '127.0.0.1,localhost',
    ).split(',')
    if host.strip()
]


# ============================================================
# CSRF TRUSTED ORIGINS
# ============================================================

# For local development this can remain empty.
#
# For deployment, set for example:
#
# CSRF_TRUSTED_ORIGINS=https://your-domain.com
#
# Multiple origins should be comma-separated.
CSRF_TRUSTED_ORIGINS = [
    origin.strip()
    for origin in os.getenv(
        'CSRF_TRUSTED_ORIGINS',
        '',
    ).split(',')
    if origin.strip()
]


# ============================================================
# APPLICATIONS
# ============================================================

INSTALLED_APPS = [
    # Django built-in applications
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # IDDS applications
    'accounts',
    'restaurant',
    'orders',
    'kitchen',
    'inventory',
    'billing',
    'reports',
    'feedback',
]


# ============================================================
# MIDDLEWARE
# ============================================================

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'inventory.middleware.LowStockLoginAlertMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# ============================================================
# URL CONFIGURATION
# ============================================================

ROOT_URLCONF = 'config.urls'


# ============================================================
# TEMPLATES
# ============================================================

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',

        # Main project-level templates folder
        'DIRS': [
            BASE_DIR / 'templates',
        ],

        'APP_DIRS': True,

        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


# ============================================================
# WSGI
# ============================================================

WSGI_APPLICATION = 'config.wsgi.application'


# ============================================================
# DATABASE
# ============================================================

# Supabase PostgreSQL
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',

        'NAME': os.getenv('DB_NAME'),
        'USER': os.getenv('DB_USER'),
        'PASSWORD': os.getenv('DB_PASSWORD'),
        'HOST': os.getenv('DB_HOST'),
        'PORT': os.getenv('DB_PORT', '5432'),

        'OPTIONS': {
            'sslmode': 'require',
        },
    }
}


# ============================================================
# PASSWORD VALIDATION
# ============================================================

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': (
            'django.contrib.auth.password_validation.'
            'UserAttributeSimilarityValidator'
        ),
    },
    {
        'NAME': (
            'django.contrib.auth.password_validation.'
            'MinimumLengthValidator'
        ),
    },
    {
        'NAME': (
            'django.contrib.auth.password_validation.'
            'CommonPasswordValidator'
        ),
    },
    {
        'NAME': (
            'django.contrib.auth.password_validation.'
            'NumericPasswordValidator'
        ),
    },
]


# ============================================================
# INTERNATIONALIZATION
# ============================================================

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_TZ = True


# ============================================================
# STATIC FILES
# ============================================================

STATIC_URL = '/static/'

# Existing project static directory.
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

# Production collection directory.
#
# This fixes:
# "You're using the staticfiles app without having set
# STATIC_ROOT to a filesystem path."
STATIC_ROOT = BASE_DIR / 'staticfiles'


# WhiteNoise production static-file storage.
STORAGES = {
    'default': {
        'BACKEND': (
            'django.core.files.storage.FileSystemStorage'
        ),
    },
    'staticfiles': {
        'BACKEND': (
            'whitenoise.storage.CompressedManifestStaticFilesStorage'
        ),
    },
}


# ============================================================
# MEDIA FILES
# ============================================================

MEDIA_URL = '/media/'

MEDIA_ROOT = BASE_DIR / 'media'


# ============================================================
# EMAIL
# ============================================================

# Development email backend.
# Emails are printed in the terminal instead of being sent.
EMAIL_BACKEND = os.getenv(
    'EMAIL_BACKEND',
    'django.core.mail.backends.console.EmailBackend',
)
EMAIL_HOST = os.getenv(
    'EMAIL_HOST',
    'smtp-relay.brevo.com',
)
EMAIL_PORT = int(
    os.getenv('EMAIL_PORT', '587')
)

EMAIL_USE_TLS = (
    os.getenv('EMAIL_USE_TLS', 'True').lower() == 'true'
)

EMAIL_HOST_USER = os.getenv(
    'EMAIL_HOST_USER',
)

EMAIL_HOST_PASSWORD = os.getenv(
    'EMAIL_HOST_PASSWORD',
)

DEFAULT_FROM_EMAIL = os.getenv(
    'DEFAULT_FROM_EMAIL',
)


# ============================================================
# AUTHENTICATION REDIRECTS
# ============================================================

# Actual login URL is under the accounts namespace.
LOGIN_URL = '/accounts/login/'

# Default fallback dashboard.
# Role-specific login logic can still override this.
LOGIN_REDIRECT_URL = '/accounts/dashboard/'

# After logout, return to the public homepage.
LOGOUT_REDIRECT_URL = '/'


# ============================================================
# PRODUCTION SECURITY
# ============================================================

# These are disabled locally by default and can be enabled
# through environment variables on the deployment platform.

SECURE_SSL_REDIRECT = (
    os.getenv('SECURE_SSL_REDIRECT', 'False').lower() == 'true'
)

SESSION_COOKIE_SECURE = (
    os.getenv('SESSION_COOKIE_SECURE', 'False').lower() == 'true'
)

CSRF_COOKIE_SECURE = (
    os.getenv('CSRF_COOKIE_SECURE', 'False').lower() == 'true'
)

SECURE_HSTS_SECONDS = int(
    os.getenv('SECURE_HSTS_SECONDS', '0')
)

SECURE_HSTS_INCLUDE_SUBDOMAINS = (
    os.getenv(
        'SECURE_HSTS_INCLUDE_SUBDOMAINS',
        'False',
    ).lower() == 'true'
)

SECURE_HSTS_PRELOAD = (
    os.getenv(
        'SECURE_HSTS_PRELOAD',
        'False',
    ).lower() == 'true'
)

SECURE_CONTENT_TYPE_NOSNIFF = True

SECURE_REFERRER_POLICY = 'same-origin'


# ============================================================
# DEFAULT PRIMARY KEY
# ============================================================

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'